config/routes.rb
AnonPersonals::Application.routes.draw do
  root to: "sessions#new"

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :personals do
    resources :messages, only: [:new, :create]
  end
  resources :messages, only: [:destroy, :index, :show]

  resources :conversations do
    resources :chats
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :body, :sender_id, :receiver_id, :personals_id, presence: true

  belongs_to(
  :sender,
  class_name: "User",
  foreign_key: :sender_id,
  primary_key: :id
  )

  belongs_to(
  :receiver,
  class_name: "User",
  foreign_key: :receiver_id,
  primary_key: :id
  )

  belongs_to(
  :personal,
  class_name: "Personal",
  foreign_key: :personals_id,
  primary_key: :id
  )

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :require_signed_in

  def new
    render :new

  end

  def create
    @message = Message.new(message_params)
    @message.sender_id = current_user.id
    @message.personals_id = params[:personal_id]
    @message.receiver_id = Personal.find(@message.personals_id).user_id

    if @message.save
      redirect_to user_url(@current_user)
    else
      flash.now[:errors] = @message.errors.full_messages
      render :new
    end
  end

  def index
    @messages = Message.where("receiver_id = ?", current_user.id)

  end

  def show
    @message = Message.find(params[:id])

    if params[:accept]
      user = User.find(@message.sender_id)
      user.partners << @current_user
      @current_user.partners << user
      @current_user.save
      user.save
      auto_confirm(@message)
      redirect_to messages_url, notice: "You can now chat with #{user.username}."
    elsif params[:reject]
      @message.destroy
      redirect_to messages_url, notice: "Message deleted"
    end


  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
    redirect_to messages_url

  end

  private

  def message_params
    params.require(:message).permit(:body, :title)
  end

  def auto_confirm(message)
    user_name = User.find(message.receiver_id)


    confirm_message = Message.new()
    confirm_message.receiver_id = message.sender_id
    confirm_message.sender_id = message.receiver_id
    confirm_message.personals_id = message.personals_id
    confirm_message.title = "Your message has been accepted!"
    confirm_message.body = "Your reply to #{message.title} was accepted. You may now chat with #{user_name.username}."

    confirm_message.save
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<h2>Inbox</h2>
<br />
<br />

<ul>
  <% @messages.each do |message| %>
    <li> <%= link_to message.title, message_url(message) %> </li>

  <% end %>
</ul>

app/views/messages/new.html.erb
<h2>New Message</h2>
<br />
<br />

<form action="<%= personal_messages_url %>" method="POST">
  <%= auth_token %>

  <label>Title
    <input type="text" name="message[title]" value="" />
  </label>

  <label>Body
    <input type="textarea" name="message[body]" value="" />
  </label>

  <input type="submit" value="Send Message" />
</form>

app/views/messages/show.html.erb
<h2><%= @message.title %> </h2>

<p>
  <%= @message.body %>
</p>

<form method="get">
  <%= auth_token %>

  <input type="submit" name="accept" value="Accept" />

  <input type="submit" name="reject" value="Reject" />
</form>