config/routes.rb
AnonPersonals::Application.routes.draw do
  root to: "sessions#new"

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :personals do
    resources :messages, only: [:new, :create]
  end
  resources :messages, only: [:destroy, :index, :show]

  resources :conversations do
    resources :chats
  end
end

app/models/personal.rb
class Personal < ActiveRecord::Base
  validates :title, :body, :user_id, :gender, :age, presence: true


  belongs_to(
  :user,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

  has_many(
  :messages,
  class_name: "Message",
  foreign_key: :personals_id,
  primary_key: :id
  )
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
  before_filter :require_signed_in

  def new
    @personal = Personal.new

  end

  def show
    @personal = Personal.find(params[:id])

  end

  def index
    @personals = Personal.all

  end

  def create
    @personal = Personal.new(personal_params)
    @personal.user_id = current_user.id
    if @personal.save
      redirect_to personal_url(@personal)
    else
      flash.now[:errors] = @personal.errors.full_messages
      render :new
    end

  end

  def edit
    @personal = Personal.find(params[:id])

  end

  def update
    @personal = Personal.find(params[:id])
    @personal.user_id = current_user.id
    if @personal.update_attributes(personal_params)
      redirect_to personal_url(@personal)
    else
      flash.now[:errors] = @personal.errors.full_messages
      render :edit
    end
  end

  def destroy
    personal = Personal.find(params[:id])
    personal.destroy
    redirect_to personals_url
  end

  private

  def personal_params
    params.require(:personal).permit(:title, :body, :location, :gender, :age)
  end
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/views/personals/index.html.erb
<body>
<main>

  <section class="content-main">

    <h2 class="page-title"> Personals</h2>

      <% @personals.each_slice(5) do |personal_row| %>
        <% personal_row.each do |personal| %>
        <a href="<%=personal_url(personal) %>">
      <div class="personal group">
        <div class="info">

      <p class="ad-title"><%= personal.title %></p>
      Gender: <%= personal.gender %>
      <br />
      Age: <%= personal.age %>
      <br />
      Location: <%= personal.location %>
    </div>
    <p class="ad--body"><%= personal.body %></p>
    </div>
  </a>
    <% end %>
    <% end %>
  </section>
</main>
</body>

app/views/personals/new.html.erb
<h2>New Personal Ad</h2>

<form action="<%= personals_url %>" method="POST">
  <%= auth_token %>

  <label>
    Title
    <input type="text" name="personal[title]" value="<%= @personal.title %>" id="title">
  </label>

  <label>
    Location (optional)
    <input type="text" name="personal[location]" value="<%= @personal.location %>" id="location">
  </label>

  <label>
    Gender
    <input type="text" name="personal[gender]" value="<%= @personal.gender %>" id="gender">
  </label>

  <label>
    Age
    <input type="text" name="personal[age]" value="<%= @personal.age %>" id="age">
  </label>

  <label>
    Body
    <input type="textarea" name="personal[body]" value="<%= @personal.body %>" id="body">
  </label>

  <input type="submit" value="Create Ad" />


</form>

app/views/personals/show.html.erb
<h2> <%=@personal.title %> </h2>


<%= link_to "Reply to Personal", new_personal_message_url(@personal) %> 