config/routes.rb
AnonPersonals::Application.routes.draw do
  root to: "sessions#new"

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :personals do
    resources :messages, only: [:new, :create]
  end
  resources :messages, only: [:destroy, :index, :show]

  resources :conversations do
    resources :chats
  end
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnonPersonals</title>
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="header group">
    <h1 class="title">Anonymous Personals</h1>

  <nav class="header-content group">

  <% if signed_in? %>
    <%= current_user.username %>
  <% else %>

    <%= link_to "Sign In", new_session_url %>
    <%= link_to "Sign Up", new_user_url %>
  <% end %>
  </nav>
  <% if signed_in? %>
    <nav class="header-sign-out">
      <%= button_to "Sign Out", session_url, :method => :delete %></nav>
  <% end %>
</header>

<% if signed_in? %>

<main>

  <section class="content-sidebar">
    <ul class="nav">
      <li><a href="<%= new_personal_url %>">Create Ad</a></li>
      <li><a href="<%= personals_url %>">Search Ads</a></li>
      <li><a href="<%= messages_url %>">Messages</a></li>
    </ul>
      <div class="chat">
        <% @current_user.partners.each do |user| %>
          <tr>
            <td>
              <%= link_to "#{user.username}", "#", class: "btn btn-success btn-xs start-conversation",
              "data-sid" => current_user.id, "data-rip" => user.id %>
            </td>
          </tr>
          <% end %>
    </div>
  </section>

</main>
 <% end %>
  <%= render "layouts/errors" %>

  <%= yield %>

  <script>


  </script>

</body>
</html>